on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    services:
      mysql:
          image: mysql:5.7
          env:
              # MYSQL_ALLOW_EMPTY_PASSWORD: yes
              MYSQL_DATABASE: ormtest
              # MYSQL_USER: user
              # MYSQL_PASSWORD: password
              MYSQL_ROOT_PASSWORD: ormtest
          ports:
              - 3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm test
        env:
            GH_ACTIONS_MYSQL_URI: "mysql://root:ormtest@localhost:${{job.services.mysql.ports[3306]}}/ormtest?multipleStatements=true"
      # - uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
